// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package bidib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BIDIB_ERR_NONE-0]
	_ = x[BIDIB_ERR_TXT-1]
	_ = x[BIDIB_ERR_CRC-2]
	_ = x[BIDIB_ERR_SIZE-3]
	_ = x[BIDIB_ERR_SEQUENCE-4]
	_ = x[BIDIB_ERR_PARAMETER-5]
	_ = x[BIDIB_ERR_BUS-16]
	_ = x[BIDIB_ERR_ADDRSTACK-17]
	_ = x[BIDIB_ERR_IDDOUBLE-18]
	_ = x[BIDIB_ERR_SUBCRC-19]
	_ = x[BIDIB_ERR_SUBTIME-20]
	_ = x[BIDIB_ERR_SUBPAKET-21]
	_ = x[BIDIB_ERR_OVERRUN-22]
	_ = x[BIDIB_ERR_HW-32]
	_ = x[BIDIB_ERR_RESET_REQUIRED-33]
	_ = x[BIDIB_ERR_NO_SECACK_BY_HOST-48]
}

const (
	_ErrorCode_name_0 = "BIDIB_ERR_NONEBIDIB_ERR_TXTBIDIB_ERR_CRCBIDIB_ERR_SIZEBIDIB_ERR_SEQUENCEBIDIB_ERR_PARAMETER"
	_ErrorCode_name_1 = "BIDIB_ERR_BUSBIDIB_ERR_ADDRSTACKBIDIB_ERR_IDDOUBLEBIDIB_ERR_SUBCRCBIDIB_ERR_SUBTIMEBIDIB_ERR_SUBPAKETBIDIB_ERR_OVERRUN"
	_ErrorCode_name_2 = "BIDIB_ERR_HWBIDIB_ERR_RESET_REQUIRED"
	_ErrorCode_name_3 = "BIDIB_ERR_NO_SECACK_BY_HOST"
)

var (
	_ErrorCode_index_0 = [...]uint8{0, 14, 27, 40, 54, 72, 91}
	_ErrorCode_index_1 = [...]uint8{0, 13, 32, 50, 66, 83, 101, 118}
	_ErrorCode_index_2 = [...]uint8{0, 12, 36}
)

func (i ErrorCode) String() string {
	switch {
	case i <= 5:
		return _ErrorCode_name_0[_ErrorCode_index_0[i]:_ErrorCode_index_0[i+1]]
	case 16 <= i && i <= 22:
		i -= 16
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 32 <= i && i <= 33:
		i -= 32
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case i == 48:
		return _ErrorCode_name_3
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
